name: om4labs
channels:
  - conda-forge
dependencies:
  - python
  - black
  - cartopy
  - dask
  - intake-xarray
  - esmf=8.0.0
  - esmpy=8.0.0
  - matplotlib
  - netcdf4
  - numpy
  - numba
  - palettable
  - pip
  - pyshp
  - pytest
  - regionmask
  - scipy
  - shapely
  - six
  - xarray
  - xesmf=0.4.0
  - xgcm
  - jupyter
  - requests 
  - aiohttp
  - graphviz
  - ipyleaflet 
  - intake
  - gcsfs
  - nc-time-axis

